### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ymgyt** [ymgyt/cli#2]
- [x] merge parent command flagset
- [x] test coverage
- [x] `curl -sSLO <target>` support
- [x] float, ints, url flag support
- [x] refactor command parse method
- [x] circleci config
- [x] coverage readme budge
- [x] README update

**Comment by ymgyt** [comment]
- [x] refactor
- [x] update test 
   - [x] help message test
   - [x] remove useless test
- [x] update README
